PIN_ROOT ?= /home/nick/arch-ntua/ex01/pin-3.22-98547-g7a303a835-gcc-linux

CONFIG_ROOT := $(PIN_ROOT)/source/tools/Config
include $(CONFIG_ROOT)/makefile.config
include makefile.rules
include $(TOOLS_ROOT)/Config/makefile.default.rules
